version: "3.5"

services:
  clickhouse01:
    image: clickhouse/clickhouse-server:23.9.1-alpine
    container_name: clickhouse01
    hostname: clickhouse01
    networks:
      ch_network:
        ipv4_address: 172.20.0.11
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ${PWD}/clickhouse01:/etc/clickhouse-server
      - ${PWD}/clickhouse01/data:/var/lib/clickhouse/data

  clickhouse02:
    image: clickhouse/clickhouse-server:23.9.1-alpine
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      ch_network:
        ipv4_address: 172.20.0.12
    volumes:
      - ${PWD}/clickhouse02:/etc/clickhouse-server
      - ${PWD}/clickhouse02/data:/var/lib/clickhouse/data

  clickhouse03:
    image: clickhouse/clickhouse-server:23.9.1-alpine
    container_name: clickhouse03
    hostname: clickhouse03
    networks:
      ch_network:
        ipv4_address: 172.20.0.13
    volumes:
      - ${PWD}/clickhouse03:/etc/clickhouse-server
      - ${PWD}/clickhouse03/data:/var/lib/clickhouse/data

  clickhouse04:
    image: clickhouse/clickhouse-server:23.9.1-alpine
    container_name: clickhouse04
    hostname: clickhouse04
    networks:
      ch_network:
        ipv4_address: 172.20.0.14
    volumes:
      - ${PWD}/clickhouse04:/etc/clickhouse-server
      - ${PWD}/clickhouse04/data:/var/lib/clickhouse/data

networks:
  ch_network:
    name: ch_network
    ipam:
      config:
        - subnet: 172.20.0.0/16